In [1]:
import logging
import hydra
import pandas as pd

from collections import defaultdict
from tqdm import tqdm 

import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import colormaps
import matplotlib.cm as cm
import matplotlib as mpl
from matplotlib.patches import Ellipse

from erc import drawing_ellipse, split_df_by_gender


logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

with hydra.initialize(version_base=None, config_path="./config"):
    cfg = hydra.compose(config_name="config", overrides={"dataset._target_=erc.datasets.KEMDy19Dataset"})
# select 1-fold 
cfg.dataset.mode = "train"
train_dataset = hydra.utils.instantiate(cfg.dataset)

cfg.dataset.mode = "valid"
cfg.dataset.validation_fold = 0
valid_dataset = hydra.utils.instantiate(cfg.dataset)

INFO:erc.utils:Instantiate KEMDy19 Dataset
INFO:erc.utils:Instantiate KEMDy19 Dataset


In [2]:

import torch
import torch.nn as nn 
import torch.nn.functional as F
from transformers import AdamW
from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor
import torch
from jiwer import wer # wer metircs 
from transformers import Wav2Vec2Processor
device = torch.device('cuda:1')




In [8]:
# Pre-training Scheme ... 
from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor, Wav2Vec2ForSequenceClassification
processor= Wav2Vec2Processor.from_pretrained("w11wo/wav2vec2-xls-r-300m-korean")
# inputs = processor(batch["wav"], sampling_rate=16000, return_tensors="pt", padding="longest") ..? 
# 그러면 마스크가 이상하게 생기는데?



pretrained_model = Wav2Vec2ForSequenceClassification.from_pretrained(
    # "wav2vec2-xls-r-300m-korean",
    "w11wo/wav2vec2-xls-r-300m-korean",
    num_labels=7
    )


Some weights of the model checkpoint at w11wo/wav2vec2-xls-r-300m-korean were not used when initializing Wav2Vec2ForSequenceClassification: ['lm_head.weight', 'lm_head.bias']
- This IS expected if you are initializing Wav2Vec2ForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForSequenceClassification were not initialized from the model checkpoint at w11wo/wav2vec2-xls-r-300m-korean and are newly initialized: ['classifier.weight', 'projector.bias', 'classifier.bias', 'projector.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for p

In [ ]:
processor

In [4]:


model = pretrained_model.to(device)
criterion = nn.MultiLabelSoftMarginLoss()
optimizer = AdamW(model.parameters(), lr = 1e-5,  eps = 1e-8)

/home/hoesungryu/.conda/envs/etri-erc/lib/python3.10/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [5]:
import torch 
from torch.utils.data import DataLoader

train_loader = DataLoader(train_dataset, batch_size= 8)

total_loss = 0
train_acc_sum = 0
train_loss = []

for batch in train_loader: 
    optimizer.zero_grad()

    inputs = {"input_values":batch['wav'],
              "attention_mask":batch['wav_mask'],
    }
    inputs = {key: inputs[key].to(device) for key in inputs}

    # print(batch.keys())
    # input_values = batch['wav']
    # attention_mask = batch['wav_mask']
    # print(input_values)
    # print(attention_mask)
    
    # inputs = processor(batch["wav"], sampling_rate=16000, return_tensors="pt")
    # labels = batch['emotion'].to("cuda")
    
    # input_values = inputs.input_values.type(torch.FloatTensor).squeeze().to("cuda")
    # print(input_values.shape)
    break
    



In [7]:
model(**inputs).logits.shape
# model(**input_dict)

OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 1; 23.70 GiB total capacity; 21.57 GiB already allocated; 6.81 MiB free; 22.06 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

In [ ]:
# from transformers import Wav2Vec2Processor, Wav2Vec2Model
# extractor = Wav2Vec2Model.from_pretrained("kresnik/wav2vec2-large-xlsr-korean")

In [ ]:
def pad_value(
        arr: torch.Tensor,
        max_length: int,
        pad_value: int | float = 0,
    ):
        """ Assumes single data """
        if not isinstance(arr, torch.Tensor):
            arr = torch.tensor(arr)
        
        mask = torch.ones(max_length).long()
        if len(arr) >= max_length:
            arr = arr[:max_length]
        else:
            null_size = max_length - len(arr)
            arr = torch.nn.functional.pad(arr, pad=(0, null_size), value=pad_value)
            mask[null_size:] = 0
        return arr, mask


In [ ]:

    def get_wav(self, wav_path: Path | str) -> torch.Tensor | np.ndarray:
        """ Get output feature vector from pre-trained wav2vec model
        XXX: Embedding outside dataset, to fine-tune pre-trained model? See Issue
        """
        wav_path = check_exists(wav_path)
        # sampling_rate, data = wavfile.read(wav_path)
        data, sampling_rate = torchaudio.load(wav_path)
        data, mask = self.pad_value(data, max_length=self.max_length_wav)
        return sampling_rate, data, mask

In [ ]:
import torchaudio 
path = "./data/KEMDy19/wav/Session01/Sess01_impro01/Sess01_impro01_F001.wav"
data, sampling_rate = torchaudio.load(path)
print(data.squeeze().shape)


In [ ]:
from scipy.io import wavfile
sampling_rate, data = wavfile.read(path)
data = torch.tensor(data)
print(data.shape)

In [ ]:
data.shape

In [ ]:
max_length_wav = 200_000
data, mask = pad_value(data, max_length=max_length_wav)

In [ ]:
data.shape

In [ ]:
data, sampling_rate

In [ ]:
# def wav2processor()

# train_dataset.map()

In [ ]:


class EmotionClassfierWithAudio(nn.Module):
    def __init__(self,pretrained_model, n_classes=7):
        super().__init__()
        self.pretrianed_model = pretrained_model
        # for p in self.pretrianed_model.parameters():
            # p.requires_grad = False

        self.fc = nn.Linear(1025,n_classes)

    def forward(self, x):
        x = F.adaptive_avg_pool3d(self.pretrianed_model(x).logits , axis=1).squeeze()# mean of 355 // logit output shape: B, Seq(355), 1025
        x = self.fc(x)
        return x

In [ ]:
# pretrained_model = Wav2Vec2ForCTC.from_pretrained("kresnik/wav2vec2-large-xlsr-korean")
pretrained_model(input_values).logits.shape

In [ ]:
model(input_values)

In [ ]:
a = extractor(batch["wav"].type(torch.FloatTensor))

In [ ]:
a.extract_features.shape

In [ ]:
a.extract_features[:,-1].shape

In [ ]:
F.adaptive_avg_pool1d(a.extract_features, output_size = 7).shape

In [ ]:

a.extract_features.

In [ ]:
model(input_values)

In [ ]:
inputs.input_values.shape

In [ ]:

    outputs = model(input_values)

    loss = criterion(outputs, labels)
    total_loss += loss.item()
    train_loss.append(total_loss/(step+1))

    loss.backward()
    optimizer.step()

avg_train_loss = total_loss / len(train_loader)
print(f'  Average training loss: {avg_train_loss:.2f}')


In [27]:
# !pip install jiwer
from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor
# import soundfile as sf
import torch
from jiwer import wer # wer metircs 
from transformers import Wav2Vec2Processor
batch = train_dataset[2]


processor = Wav2Vec2Processor.from_pretrained("kresnik/wav2vec2-large-xlsr-korean")
inputs = processor(batch["wav"], sampling_rate=16000, return_tensors="pt", return_attention_mask = False,
                #    padding="longest"
                   )

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [28]:
inputs.keys()

dict_keys(['input_values'])

In [30]:
inputs['input_values']

tensor([[-2.8949e-03, -1.6477e-03, -8.8694e-05,  ..., -2.4791e-03,
         -2.4791e-03, -2.4791e-03]])

In [18]:
batch.keys()

dict_keys(['sampling_rate', 'wav', 'wav_mask', 'txt', 'txt_mask', 'emotion', 'valence', 'arousal', 'gender'])

In [10]:
batch['wav']

tensor([-0.0001,  0.0002,  0.0007,  ...,  0.0000,  0.0000,  0.0000])

In [19]:
batch['wav_mask']

tensor([1, 1, 1,  ..., 0, 0, 0])

In [23]:
batch['wav_mask'].shape

torch.Size([200000])

In [29]:
inputs['attention_mask'].squeeze()


KeyError: 'attention_mask'

In [22]:
inputs['attention_mask'].shape

torch.Size([1, 200000])

In [ ]:



model = Wav2Vec2ForCTC.from_pretrained("kresnik/wav2vec2-large-xlsr-korean").to('cuda')

input_values = inputs.input_values
print(input_values.shape)
with torch.no_grad():
    logits = model(input_values.type(torch.FloatTensor).to("cuda")).logits
predicted_ids = torch.argmax(logits, dim=-1)
transcription = processor.batch_decode(predicted_ids)
print(batch['txt'])
print(transcription)
print("WER:", wer(batch['txt'], transcription))

In [ ]:
logits.shape

In [ ]:
logits[:,-1].shape

In [ ]:
logits.shape

In [ ]:
logits.mean(axis=1).shape

In [ ]:
logits[:,-1]

In [ ]:
logits

In [ ]:
logits

In [ ]:
model(input_values.type(torch.FloatTensor).to("cuda"))

In [ ]:
predicted_ids